// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type EnqueStatus interface {
	IsEnqueStatus()
}

type EnqueError struct {
	IPAddress    string `json:"ip_address"`
	ErrorMessage string `json:"error_message"`
}

func (EnqueError) IsEnqueStatus() {}

type EnqueSuccess struct {
	IP *IP `json:"ip"`
}

func (EnqueSuccess) IsEnqueStatus() {}

type IP struct {
	UUID         string    `json:"uuid"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ResponseCode string    `json:"response_code"`
	IPAddress    string    `json:"ip_address"`
}
