// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Status interface {
	IsStatus()
}

type Error struct {
	IPAddress    string `json:"ip_address"`
	ErrorMessage string `json:"error_message"`
	ErrorCode    string `json:"error_code"`
}

type ErrorStatus struct {
	Error *Error `json:"error"`
}

func (ErrorStatus) IsStatus() {}

type IP struct {
	UUID         string    `json:"uuid"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ResponseCode string    `json:"response_code"`
	IPAddress    string    `json:"ip_address"`
}

type SuccessStatus struct {
	IP *IP `json:"ip"`
}

func (SuccessStatus) IsStatus() {}
